### ISSUE TITLE
How to run demo in windows?

### ISSUE THREAD

**Issue by JustinhoCHN** [limuhit/CCN#3]
Hi, thanks for your work, may I ask how to run demo in win10? According to your README, 
> In the folder of "binary", the codes can be directly runed on windows is given. 

Does it meaning we can just run ```python .\scae.py -i test.png -o test.data -s test.shape -e -gpu 0 -q 0``` **without install any independices**? As long as I have NVIDIA graphics card and CUDA installed.

But error raised:

```
(CCN) D:\projects\CCN\binary>python .\scae.py -i test.png -o test.data -s test.shape -e -gpu 0 -q 0
Traceback (most recent call last):
  File ".\scae.py", line 2, in <module>
    import Coder
ImportError: DLL load failed: %1 不是有效的 Win32 应用程序。
```

Or do I need to compile caffe first? The instructions in README is quite confusing.

**Comment by limuhit** [comment]
Compile the arithmetic coder in https://github.com/limuhit/CCN/tree/master/ae.

**Comment by JustinhoCHN** [comment]
> Compile the arithmetic coder in https://github.com/limuhit/CCN/tree/master/ae.

Thank you, and I suggest to put these necessary steps in RAEDME.

**Comment by limuhit** [comment]
I have the compiled arithmetic coder and put it in https://github.com/limuhit/CCN/tree/master/binary. Maybe the environment is different from my computer.
