### ISSUE TITLE
Some questions about the encoding and decoding pipeline.

### ISSUE THREAD

**Issue by JustinhoCHN** [limuhit/CCN#4]
Hi mu, I've read the details of your CCN paper and the code, I want to make sure that I understand it correctly, here're my understanding, correct me if I'm wrong.

1. The encode prototxt ```gmm_4_deploy_encoder.prototxt``` is for this pipeline: ```generating code block y -> compute the P(y) via CCN model -> Arithmetic encoding using y and P(y) -> generate bitstream```

2. The decode prototxt ```gmm_4_deploy_decoder.prototxt``` is just for ```Arithmetic decoding -> restore image via CCN```

3. The caffe depoly prototxt ```gmm_4_deploy.prototxt``` contains the full pipeline: ```generating code block y -> compute the P(y) via CCN model -> Arithmetic encoding using y and P(y) -> generate bitstream -> Arithmetic decoding -> restore image via CCN```

4. The ```extract_codes.py``` in ```cmp/``` is for generating arithmetic code right?

**Comment by limuhit** [comment]
1. gmm_4_deploy_encoder.prototxt: generating code block y -> compute the P(y) via CCN model
2. gmm_4_deploy_decoder.prototxt: y ->  restore image via CCN
3. gmm_4_deploy.prototxt: generating code block y -> compute the P(y) via CCN model ->  restore image via CCN
4.  
 (1) We pre-train the encoder and decoder with "https://github.com/limuhit/CCN/blob/master/cmp/train_base.py". 
 (2) We extract the pre-trained code block y with "https://github.com/limuhit/CCN/blob/master/cmp/extract_codes.py". 
 (3) We pre-train the entropy model P(y) with the extracted code blocks. "https://github.com/limuhit/CCN/blob/master/cmp/train_lossless.py"
 (4) Initialize the encdoer, decoder and P() with the pre-trained parameters and then jointly train them. https://github.com/limuhit/CCN/blob/master/cmp/train_gmm.py
Here, extract_codes.py is used in (2) to extract the pre-trained y.

5. The version with arithmetic encoding and decoding can be find at https://github.com/limuhit/CCN/tree/master/binary/model.
(1) encoder_4.prototxt:  image x -> code block y 
(2) lossless_encoder_4.prototxt:  y -> P(y) for arithmetic encoding.
(3) lossless_decoder_4.prototxt:  arithmetic decoding
(4) decoder_4.prototxt:  code block y -> decoded image .
(5) The pipeline is shown in https://github.com/limuhit/CCN/blob/master/binary/scae.py. And "Coder.pyd" is the python library for arithmetic coding whose source code can be found at https://github.com/limuhit/CCN/tree/master/ae.

**Comment by JustinhoCHN** [comment]
@limuhit Thanks for your reply, I'd to ask that if the arithmetic coding source code is exactly the same as https://github.com/nayuki/Reference-arithmetic-coding/tree/master/cpp ? I want to import the Coder in ubuntu python, the Coder.pyd file was compiled under windows, which I can't import it directly. If you didn't change anything from nayuki's original code, maybe I can use the python lib that nayuki supplied.

**Comment by limuhit** [comment]
Arithmetic coding is modified to fill my requirements and can be found at https://github.com/limuhit/CCN/tree/master/ae.
You would compile the source code under ubuntu. Actually, I knew someone who had compiled it under ubuntu successfully.

**Comment by JustinhoCHN** [comment]
> Arithmetic coding is modified to fill my requirements and can be found at https://github.com/limuhit/CCN/tree/master/ae.
> You would compile the source code under ubuntu. Actually, I knew someone who had compiled it under ubuntu successfully.

Thank you. I'm trying to compile the source code,

```
g++ -fPIC -shared -o libae.so ArithmeticCoder.cpp BitIoStream.cpp python.cpp -I /home/ubuntu/anaconda3/envs/CCN/lib/python2.7/site-packages/numpy/core/include/
```
Compile successfully, I got the ```libae.so``` file:
```
.
├── ArithmeticCoder.cpp
├── ArithmeticCoder.h
├── BitIoStream.cpp
├── BitIoStream.h
├── CMakeLists.txt
├── coder.h
├── Coder.vcxproj
├── Coder.vcxproj.filters
├── Coder.vcxproj.user
├── libae.so
├── python.cpp
└── x64
```

but when I try to import it with python:

```
>>> import ctypes
>>> so = ctypes.cdll.LoadLibrary('./libae.so')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/ctypes/__init__.py", line 440, in LoadLibrary
    return self._dlltype(name)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: ./libae.so: undefined symbol: _ZNK5boost6python7objects21py_function_impl_base9max_arityEv
```

The error message says I didn't link the function correctly, can you please give a hit about how to compile the .so file correctly? Or could you please ask the guy who had compiled it under ubuntu successfully for me? Thanks.

**Comment by limuhit** [comment]
Rename libae.so as Coder.pyd.
Just "import Coder" in python.

**Comment by JustinhoCHN** [comment]
@limuhit Thank you, I get it done. I post my pipeline here, in case someone need it:

```
cd ./CCN/ae/Coder

g++ -fpic -c python.cpp -I /usr/lib/python2.7/site-packages/numpy/core/include/ -I /usr/include/boost -I /usr/include/python2.7 -lpython2.7 -lboost_python-py27

g++ -fpic -c ArithmeticCoder.cpp

g++ -fpic -c BitIoStream.cpp

g++ -shared -o Coder.so python.o ArithmeticCoder.o BitIoStream.o -I /usr/lib/python2.7/site-packages/numpy/core/include/ -I /usr/include/boost -I /usr/include/python2.7 -lpython2.7 -lboost_python-py27
```

Import it successfully.

```
Python 2.7.18 |Anaconda, Inc.| (default, Apr 23 2020, 22:42:48) 
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import Coder
>>> coder = Coder.coder('./test.data')
```
