### ISSUE TITLE
Image decoded by Scae.py from bit stream looks weird.

### ISSUE THREAD

**Issue by JustinhoCHN** [limuhit/CCN#5]
I tried to encode the image to bit stream and then decode the image from the bit stream, got the following result:

Original test png image:
![test png image](https://user-images.githubusercontent.com/24873787/89153947-861cc880-d598-11ea-8aed-10965513f725.png)

Decoding image from bit stream:
![test_out decoded image](https://user-images.githubusercontent.com/24873787/89153950-887f2280-d598-11ea-8ad2-9c3f55613765.png)

My command to encode and decode:

```
python scae.py -i test.png -o test.data -s test.shape -e -gpu 0 -q 0
python scae.py -i test.data -o test_out.png -s test.shape -d -gpu 1
```

Some files generate by the scae.py:
```
3.2K 8月   3 14:30 test.data
724K 8月   3 14:30 test_out.png
   4 8月   3 14:30 test.shape
```

I didn't change any code in scae.py, the ae module is compiled correctly under ubuntu, no any error raised. Why this decoded image look so weird? Can you provide your result here?

**Comment by limuhit** [comment]
Try it several times. This is due to the accuracy of the floating-point number. For the same image and parameters, it would occur 0.499999 and 0.50000001 in two separate runnings.  In quantization, the first would be 0 and the other would be 1. Such a problem would happen in arithmetic encoding and decoding. A single mistake like this will make all of the following codes are wrong.  Try the ending and decoding several times.

**Comment by JustinhoCHN** [comment]
@limuhit I found that the encoding and decoding phase using different model, does it matter?

Encoding phase using ```4.caffemodel``` :
```
(CCN) ubuntu@user-Super-Server:~/projects/CCN/extract_ae$ GLOG_minloglevel=1 python scae.py -i test.png -o test.data -s test.shape -e -gpu 1 -q 0
WARNING: Logging before InitGoogleLogging() is written to STDERR
W0803 15:23:06.492677 28524 _caffe.cpp:147] DEPRECATION WARNING - deprecated use of Python interface
W0803 15:23:06.492712 28524 _caffe.cpp:148] Use this instead (with the named "weights" parameter):
W0803 15:23:06.492718 28524 _caffe.cpp:150] Net('./model/encoder_4.prototxt', 1, weights='./model/4.caffemodel')
W0803 15:23:06.494557 28524 upgrade_proto.cpp:72] Note that future Caffe releases will only support input layers and not input fields.
W0803 15:23:08.705837 28524 _caffe.cpp:147] DEPRECATION WARNING - deprecated use of Python interface
W0803 15:23:08.705866 28524 _caffe.cpp:148] Use this instead (with the named "weights" parameter):
W0803 15:23:08.705886 28524 _caffe.cpp:150] Net('./model/lossless_4_encoder.prototxt', 1, weights='./model/code_4.caffemodel')
W0803 15:23:08.706156 28524 upgrade_proto.cpp:72] Note that future Caffe releases will only support input layers and not input fields.
23312
0.183978796005
```

Decoding phase using ```8.caffemodel```:
```
(CCN) ubuntu@user-Super-Server:~/projects/CCN/extract_ae$ GLOG_minloglevel=1 python scae.py -i test.data -o test_out.png -s test.shape -d -gpu 1
WARNING: Logging before InitGoogleLogging() is written to STDERR
W0803 15:23:13.787109 28941 _caffe.cpp:147] DEPRECATION WARNING - deprecated use of Python interface
W0803 15:23:13.787160 28941 _caffe.cpp:148] Use this instead (with the named "weights" parameter):
W0803 15:23:13.787165 28941 _caffe.cpp:150] Net('./model/lossless_8_decoder.prototxt', 1, weights='./model/code_8.caffemodel')
W0803 15:23:13.788944 28941 upgrade_proto.cpp:72] Note that future Caffe releases will only support input layers and not input fields.
W0803 15:23:14.309108 28941 _caffe.cpp:147] DEPRECATION WARNING - deprecated use of Python interface
W0803 15:23:14.309130 28941 _caffe.cpp:148] Use this instead (with the named "weights" parameter):
W0803 15:23:14.309149 28941 _caffe.cpp:150] Net('./model/decoder.prototxt', 1, weights='./model/8.caffemodel')
W0803 15:23:14.309594 28941 upgrade_proto.cpp:72] Note that future Caffe releases will only support input layers and not input fields.
```

**Comment by limuhit** [comment]
It matters. You should use the same model.

**Comment by JustinhoCHN** [comment]
@limuhit I got it, we should add **```-q 0```** for **decoding** command, 

```
python scae.py -i test.data -o test_out.png -s test.shape -d -gpu 1 -q 0
```

Rather than:

```
python scae.py -i test.data -o test_out.png -s test.shape -d -gpu 1
```

Maybe you should modify the readme.

Finally I get the result:

Hardware & software: RTX 2080Ti, CUDA10.0

Test image (b64encoding bytes: 796097, image size: 583kb):
![test](https://user-images.githubusercontent.com/24873787/89159982-def15e80-d5a2-11ea-9031-84d15570f4a1.png)


```4.caffemodel```: (bytes: 23313, encoding time: 0.20s, image size: 338kb, bit stream compression rate: **34.15**)
![test_out](https://user-images.githubusercontent.com/24873787/89158532-d6982400-d5a0-11ea-83d2-b99562beed10.png)

```8.caffemodel```: (bytes: 46624, encoding time: 0.34s, image size: 393kb, bit stream compression rate: **17.07**)
![test_out_8](https://user-images.githubusercontent.com/24873787/89159209-c765a600-d5a1-11ea-8c1a-86cf3dc21b5e.png)

```14.caffemodel```: (bytes: 81592, encoding time: 0.52s, image size: 447kb, bit stream compression rate: **9.76**)
![test_out_14](https://user-images.githubusercontent.com/24873787/89159236-cdf41d80-d5a1-11ea-9df7-619df38b33b3.png)

That's impressive! Great work!
